version: '3.7'

services:
    web:
        build: .
        command: gunicorn wsgi:app --bind 0.0.0.0:5000
        restart: always
        ports:
            - '5000:5000'
        env_file:
            - .env
